### ISSUE TITLE
java.lang.NoClassDefFoundError when using Twitch launcher

### ISSUE THREAD

**Issue by Dummiesman** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#35]
Made a new 1.15.1 forge profile in twitch launcher, installed CCI 1.15.1, and it refuses to load. No other mods installed.

forge-30.0.51

`[23:36:28] [modloading-worker-1/ERROR]: Failed to create mod instance. ModID: contentcreatorintegration, class me.ichun.mods.cci.common.ContentCreatorIntegration
java.lang.NoClassDefFoundError: net/minecraftforge/fml/config/ModConfig$ConfigReloading
	at me.ichun.mods.cci.common.ContentCreatorIntegration$ConfigClient.<init>(ContentCreatorIntegration.java:284) ~[?:1.2.3]
	at me.ichun.mods.cci.common.ContentCreatorIntegration.lambda$null$1(ContentCreatorIntegration.java:103) ~[?:1.2.3]
	at me.ichun.mods.cci.common.ContentCreatorIntegration$$Lambda$2215/937536615.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.DistExecutor.runWhenOn(DistExecutor.java:56) ~[?:?]
	at me.ichun.mods.cci.common.ContentCreatorIntegration.<init>(ContentCreatorIntegration.java:101) ~[?:1.2.3]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) [?:30.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2151/1401589925.accept(Unknown Source) [?:30.0]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2150/1631805946.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2150/1631805946.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2202/906340269.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) [?:1.8.0_51]
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$11(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2200/1488311804.run(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.config.ModConfig$ConfigReloading
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 39 more`

**Comment by Shindur** [comment]
Getting a similar issue on forge 31.1.30 for 1.15.2

java.lang.NoClassDefFoundError: net/minecraftforge/fml/config/ModConfig$ConfigReloading
	at me.ichun.mods.cci.common.ContentCreatorIntegration$ConfigClient.<init>(ContentCreatorIntegration.java:284) ~[?:1.2.3]
	at me.ichun.mods.cci.common.ContentCreatorIntegration.lambda$null$1(ContentCreatorIntegration.java:103) ~[?:1.2.3]
	at me.ichun.mods.cci.common.ContentCreatorIntegration$$Lambda$4121/1354844193.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.DistExecutor.runWhenOn(DistExecutor.java:56) ~[?:?]
	at me.ichun.mods.cci.common.ContentCreatorIntegration.<init>(ContentCreatorIntegration.java:101) ~[?:1.2.3]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) [?:31.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2226/1547299892.accept(Unknown Source) [?:31.1]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2225/6096495.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2225/6096495.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2486/467764138.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.config.ModConfig$ConfigReloading
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 28 more

**Comment by Shindur** [comment]
Seems the issue may be for 1.15.2 that it's downloading the 1.15.1 version... after navigating through the twitch launcher and going to the downloads area I was able to grab the 1.15.2 version and it fixed my issue.

**Comment by iChun** [comment]
There's a 1.15.2. native version now. Should have sorted that crash out. Thanks for the report! I'll be pushing out version 1.2.4 sometime later today as well so look out for that.
