### ISSUE TITLE
Error Processing Chat - YouTube Chat

### ISSUE THREAD

**Issue by Allybe** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#93]
Hello! I am running into issues with YouTube Chat. It seems after a while of using the mod on stream we get the "Error Processing Chat". Seems like we are getting back error 403 from the YouTube API, mostly with the `youtube.api.v3.V3DataSearchService.List` thingy, but the error is most likely coming from the `youtube.api.v3.V3DataLiveChatMessageService.List` request. 

![image](https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/assets/67673392/83ea1f08-aa0d-411f-8133-997b8061699e)

![image](https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/assets/67673392/055a2380-d07b-4489-ac14-d21b2a014380)

Logs: 
```
[21:21:31] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://youtube.googleapis.com/youtube/v3/liveChat/messages?part=id,snippet,authorDetails&liveChatId=Cg0KC3hyNmwyM3JLcDMwKicKGFVDZkxuQVMzLWUyMkxKNFNyMzJTU241QRILeHI2bDIzcktwMzA&key=[REDACTED]&pageToken=GKKPo4_cuIMDIOCThJbcuIMD
[21:21:31] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2000)
[21:21:31] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[21:21:31] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[21:21:31] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[21:21:31] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at me.ichun.mods.cci.common.module.youtube.ThreadYoutubeChatSocket.run(ThreadYoutubeChatSocket.java:187)
[21:21:36] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://youtube.googleapis.com/youtube/v3/liveChat/messages?part=id,snippet,authorDetails&liveChatId=Cg0KC3hyNmwyM3JLcDMwKicKGFVDZkxuQVMzLWUyMkxKNFNyMzJTU241QRILeHI2bDIzcktwMzA&key=[REDACTED]&pageToken=GKKPo4_cuIMDIOCThJbcuIMD
[21:21:36] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2000)
[21:21:36] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[21:21:36] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[21:21:36] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[21:21:36] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at me.ichun.mods.cci.common.module.youtube.ThreadYoutubeChatSocket.run(ThreadYoutubeChatSocket.java:187)
[21:21:42] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://youtube.googleapis.com/youtube/v3/liveChat/messages?part=id,snippet,authorDetails&liveChatId=Cg0KC3hyNmwyM3JLcDMwKicKGFVDZkxuQVMzLWUyMkxKNFNyMzJTU241QRILeHI2bDIzcktwMzA&key=[REDACTED]&pageToken=GKKPo4_cuIMDIOCThJbcuIMD
[21:21:42] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2000)
[21:21:42] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[21:21:42] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[21:21:42] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[21:21:42] [CCI - YouTubeChat - 1 Integration/INFO]: [STDERR]: 	at me.ichun.mods.cci.common.module.youtube.ThreadYoutubeChatSocket.run(ThreadYoutubeChatSocket.java:187)
```

**Comment by Allybe** [comment]
Also, I'd love to see this mod open sourced. For people to add platforms as they want!

**Comment by Allybe** [comment]
Seems to be a rate limit issue

![image](https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/assets/67673392/b003529e-a3ef-4b84-bd9a-8542f1836e60)

**Comment by iChun** [comment]
I'm afraid that this is a known issue with YT chat using up queries (when it shouldn't), unfortunately I've not had the chance to look into this as of late, and afaik there is no way around the free dev account limit asides from paying for a higher query limit with google devs (which I personally wouldn't recommend. I also haven't had anyone actually do this to increase the limit and report back to me so I don't know if it will actually work).

I aim to look into this for the next major revision of CCI (as well as open up more parts of CCI to allow for other people to add their own levels of support), but I can't guarantee when this will happen

**Comment by Allybe** [comment]
Ah, at least it's a known issue. I would try to get a higher quota limit but that doesn't seem worth it since I'm not making any money off streaming. I'll look into making my own... hacky way of doing this.
